/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models;

import org.frostbite.karren.Karren;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Database extends org.jooq.impl.SchemaImpl {

	/**
	 * The singleton instance of <code>Database</code>
	 */
	public static final Database DATABASE = new Database();

	/**
	 * No further instances allowed
	 */
	private Database() {
		super(Karren.conf.getSqldb());
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ,
			org.frostbite.karren.Database.Models.tables.Songdb.SONGDB,
			org.frostbite.karren.Database.Models.tables.Userfaves.USERFAVES,
			org.frostbite.karren.Database.Models.tables.Users.USERS,
			org.frostbite.karren.Database.Models.tables.WordCounts.WORD_COUNTS);
	}
}
