/*
 * Copyright (c) 2017 Owen Bennett.
 *  You may use, distribute and modify this code under the terms of the MIT licence.
 *  You should have obtained a copy of the MIT licence with this software,
 *  if not please obtain one from https://opensource.org/licences/MIT
 *
 *
 *
 */

/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.tables.Favorites;
import org.frostbite.karren.Database.Models.tables.Guild;
import org.frostbite.karren.Database.Models.tables.Interaction;
import org.frostbite.karren.Database.Models.tables.Interactionfailuretemplate;
import org.frostbite.karren.Database.Models.tables.Interactionpermissionerrortemplate;
import org.frostbite.karren.Database.Models.tables.Interactionsuccesstemplate;
import org.frostbite.karren.Database.Models.tables.Interactiontag;
import org.frostbite.karren.Database.Models.tables.InteractiontagHasInteraction;
import org.frostbite.karren.Database.Models.tables.Interactiontemplate;
import org.frostbite.karren.Database.Models.tables.Interactiontriggers;
import org.frostbite.karren.Database.Models.tables.Interactionvoicefile;
import org.frostbite.karren.Database.Models.tables.Songdb;
import org.frostbite.karren.Database.Models.tables.User;
import org.frostbite.karren.Database.Models.tables.Wordcounts;
import org.frostbite.karren.Karren;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Karrendb extends SchemaImpl {

	private static final long serialVersionUID = 341498274;

	/**
	 * The reference instance of <code>KarrenDB</code>
	 */
	public static final Karrendb KARRENDB = new Karrendb();

	/**
	 * No further instances allowed
	 */
	private Karrendb() {
		super(Karren.conf.getSqldb());
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Favorites.FAVORITES,
			Guild.GUILD,
			Interaction.INTERACTION,
			Interactionfailuretemplate.INTERACTIONFAILURETEMPLATE,
			Interactionpermissionerrortemplate.INTERACTIONPERMISSIONERRORTEMPLATE,
			Interactionsuccesstemplate.INTERACTIONSUCCESSTEMPLATE,
			Interactiontag.INTERACTIONTAG,
			InteractiontagHasInteraction.INTERACTIONTAG_HAS_INTERACTION,
			Interactiontemplate.INTERACTIONTEMPLATE,
			Interactiontriggers.INTERACTIONTRIGGERS,
			Interactionvoicefile.INTERACTIONVOICEFILE,
			Songdb.SONGDB,
			User.USER,
			Wordcounts.WORDCOUNTS);
	}
}
