/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>database</code>
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord, java.lang.Integer> IDENTITY_RADIO_DJ = Identities0.IDENTITY_RADIO_DJ;
	public static final org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.SongdbRecord, java.lang.Integer> IDENTITY_SONGDB = Identities0.IDENTITY_SONGDB;
	public static final org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord, java.lang.Integer> IDENTITY_USERFAVES = Identities0.IDENTITY_USERFAVES;
	public static final org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.UsersRecord, java.lang.Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;
	public static final org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord, java.lang.Integer> IDENTITY_WORD_COUNTS = Identities0.IDENTITY_WORD_COUNTS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord> KEY_RADIO_DJ_PRIMARY = UniqueKeys0.KEY_RADIO_DJ_PRIMARY;
	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord> KEY_RADIO_DJ_UNIQ_982FE985774A00A = UniqueKeys0.KEY_RADIO_DJ_UNIQ_982FE985774A00A;
	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.SongdbRecord> KEY_SONGDB_PRIMARY = UniqueKeys0.KEY_SONGDB_PRIMARY;
	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord> KEY_USERFAVES_PRIMARY = UniqueKeys0.KEY_USERFAVES_PRIMARY;
	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord> KEY_WORD_COUNTS_PRIMARY = UniqueKeys0.KEY_WORD_COUNTS_PRIMARY;
	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord> KEY_WORD_COUNTS_WORD = UniqueKeys0.KEY_WORD_COUNTS_WORD;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord, java.lang.Integer> IDENTITY_RADIO_DJ = createIdentity(org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ, org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ.ID);
		public static org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.SongdbRecord, java.lang.Integer> IDENTITY_SONGDB = createIdentity(org.frostbite.karren.Database.Models.tables.Songdb.SONGDB, org.frostbite.karren.Database.Models.tables.Songdb.SONGDB.ID);
		public static org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord, java.lang.Integer> IDENTITY_USERFAVES = createIdentity(org.frostbite.karren.Database.Models.tables.Userfaves.USERFAVES, org.frostbite.karren.Database.Models.tables.Userfaves.USERFAVES.ID);
		public static org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.UsersRecord, java.lang.Integer> IDENTITY_USERS = createIdentity(org.frostbite.karren.Database.Models.tables.Users.USERS, org.frostbite.karren.Database.Models.tables.Users.USERS.IRCUSERID);
		public static org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord, java.lang.Integer> IDENTITY_WORD_COUNTS = createIdentity(org.frostbite.karren.Database.Models.tables.WordCounts.WORD_COUNTS, org.frostbite.karren.Database.Models.tables.WordCounts.WORD_COUNTS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord> KEY_RADIO_DJ_PRIMARY = createUniqueKey(org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ, org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ.ID);
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord> KEY_RADIO_DJ_UNIQ_982FE985774A00A = createUniqueKey(org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ, org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ.CONNECTNAME);
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.SongdbRecord> KEY_SONGDB_PRIMARY = createUniqueKey(org.frostbite.karren.Database.Models.tables.Songdb.SONGDB, org.frostbite.karren.Database.Models.tables.Songdb.SONGDB.ID);
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord> KEY_USERFAVES_PRIMARY = createUniqueKey(org.frostbite.karren.Database.Models.tables.Userfaves.USERFAVES, org.frostbite.karren.Database.Models.tables.Userfaves.USERFAVES.ID);
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.UsersRecord> KEY_USERS_PRIMARY = createUniqueKey(org.frostbite.karren.Database.Models.tables.Users.USERS, org.frostbite.karren.Database.Models.tables.Users.USERS.IRCUSERID);
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord> KEY_WORD_COUNTS_PRIMARY = createUniqueKey(org.frostbite.karren.Database.Models.tables.WordCounts.WORD_COUNTS, org.frostbite.karren.Database.Models.tables.WordCounts.WORD_COUNTS.ID);
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord> KEY_WORD_COUNTS_WORD = createUniqueKey(org.frostbite.karren.Database.Models.tables.WordCounts.WORD_COUNTS, org.frostbite.karren.Database.Models.tables.WordCounts.WORD_COUNTS.WORD);
	}
}
