/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>KarrenDB</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.FavoritesRecord, java.lang.Integer> IDENTITY_FAVORITES = Identities0.IDENTITY_FAVORITES;
	public static final org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.SongdbRecord, java.lang.Integer> IDENTITY_SONGDB = Identities0.IDENTITY_SONGDB;
	public static final org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord, java.lang.Integer> IDENTITY_WORDCOUNTS = Identities0.IDENTITY_WORDCOUNTS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.FavoritesRecord> KEY_FAVORITES_PRIMARY = UniqueKeys0.KEY_FAVORITES_PRIMARY;
	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.SongdbRecord> KEY_SONGDB_PRIMARY = UniqueKeys0.KEY_SONGDB_PRIMARY;
	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.SongdbRecord> KEY_SONGDB_SONGTITLE = UniqueKeys0.KEY_SONGDB_SONGTITLE;
	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord> KEY_WORDCOUNTS_PRIMARY = UniqueKeys0.KEY_WORDCOUNTS_PRIMARY;
	public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord> KEY_WORDCOUNTS_WORD = UniqueKeys0.KEY_WORDCOUNTS_WORD;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<org.frostbite.karren.Database.Models.tables.records.FavoritesRecord, org.frostbite.karren.Database.Models.tables.records.SongdbRecord> FK_FAVORITES_SONGDB = ForeignKeys0.FK_FAVORITES_SONGDB;
	public static final org.jooq.ForeignKey<org.frostbite.karren.Database.Models.tables.records.FavoritesRecord, org.frostbite.karren.Database.Models.tables.records.UserRecord> FK_FAVORITES_USER = ForeignKeys0.FK_FAVORITES_USER;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.FavoritesRecord, java.lang.Integer> IDENTITY_FAVORITES = createIdentity(org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES, org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES.FAVEID);
		public static org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.SongdbRecord, java.lang.Integer> IDENTITY_SONGDB = createIdentity(org.frostbite.karren.Database.Models.tables.Songdb.SONGDB, org.frostbite.karren.Database.Models.tables.Songdb.SONGDB.ID);
		public static org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord, java.lang.Integer> IDENTITY_WORDCOUNTS = createIdentity(org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS, org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS.WORDID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.FavoritesRecord> KEY_FAVORITES_PRIMARY = createUniqueKey(org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES, org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES.FAVEID);
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.SongdbRecord> KEY_SONGDB_PRIMARY = createUniqueKey(org.frostbite.karren.Database.Models.tables.Songdb.SONGDB, org.frostbite.karren.Database.Models.tables.Songdb.SONGDB.ID);
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.SongdbRecord> KEY_SONGDB_SONGTITLE = createUniqueKey(org.frostbite.karren.Database.Models.tables.Songdb.SONGDB, org.frostbite.karren.Database.Models.tables.Songdb.SONGDB.SONGTITLE);
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.UserRecord> KEY_USER_PRIMARY = createUniqueKey(org.frostbite.karren.Database.Models.tables.User.USER, org.frostbite.karren.Database.Models.tables.User.USER.USERID);
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord> KEY_WORDCOUNTS_PRIMARY = createUniqueKey(org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS, org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS.WORDID);
		public static final org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord> KEY_WORDCOUNTS_WORD = createUniqueKey(org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS, org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS.WORD);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<org.frostbite.karren.Database.Models.tables.records.FavoritesRecord, org.frostbite.karren.Database.Models.tables.records.SongdbRecord> FK_FAVORITES_SONGDB = createForeignKey(org.frostbite.karren.Database.Models.Keys.KEY_SONGDB_PRIMARY, org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES, org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES.SONGID);
		public static final org.jooq.ForeignKey<org.frostbite.karren.Database.Models.tables.records.FavoritesRecord, org.frostbite.karren.Database.Models.tables.records.UserRecord> FK_FAVORITES_USER = createForeignKey(org.frostbite.karren.Database.Models.Keys.KEY_USER_PRIMARY, org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES, org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES.USERID);
	}
}
