/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in KarrenDB
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table KarrenDB.Favorites
	 */
	public static final org.frostbite.karren.Database.Models.tables.Favorites FAVORITES = org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES;

	/**
	 * The table KarrenDB.songdb
	 */
	public static final org.frostbite.karren.Database.Models.tables.Songdb SONGDB = org.frostbite.karren.Database.Models.tables.Songdb.SONGDB;

	/**
	 * The table KarrenDB.User
	 */
	public static final org.frostbite.karren.Database.Models.tables.User USER = org.frostbite.karren.Database.Models.tables.User.USER;

	/**
	 * The table KarrenDB.WordCounts
	 */
	public static final org.frostbite.karren.Database.Models.tables.Wordcounts WORDCOUNTS = org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS;
}
