/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in database
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table database.radio_dj
	 */
	public static final org.frostbite.karren.Database.Models.tables.RadioDj RADIO_DJ = org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ;

	/**
	 * The table database.songdb
	 */
	public static final org.frostbite.karren.Database.Models.tables.Songdb SONGDB = org.frostbite.karren.Database.Models.tables.Songdb.SONGDB;

	/**
	 * The table database.userfaves
	 */
	public static final org.frostbite.karren.Database.Models.tables.Userfaves USERFAVES = org.frostbite.karren.Database.Models.tables.Userfaves.USERFAVES;

	/**
	 * The table database.users
	 */
	public static final org.frostbite.karren.Database.Models.tables.Users USERS = org.frostbite.karren.Database.Models.tables.Users.USERS;

	/**
	 * The table database.word_counts
	 */
	public static final org.frostbite.karren.Database.Models.tables.WordCounts WORD_COUNTS = org.frostbite.karren.Database.Models.tables.WordCounts.WORD_COUNTS;
}
