/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FavoritesRecord extends org.jooq.impl.UpdatableRecordImpl<org.frostbite.karren.Database.Models.tables.records.FavoritesRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Long> {

	private static final long serialVersionUID = -1186954259;

	/**
	 * Setter for <code>KarrenDB.Favorites.FaveID</code>.
	 */
	public void setFaveid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>KarrenDB.Favorites.FaveID</code>.
	 */
	public java.lang.Integer getFaveid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>KarrenDB.Favorites.SongID</code>.
	 */
	public void setSongid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>KarrenDB.Favorites.SongID</code>.
	 */
	public java.lang.Integer getSongid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>KarrenDB.Favorites.UserID</code>.
	 */
	public void setUserid(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>KarrenDB.Favorites.UserID</code>.
	 */
	public java.lang.Long getUserid() {
		return (java.lang.Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Long> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Long> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES.FAVEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES.SONGID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getFaveid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getSongid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FavoritesRecord value1(java.lang.Integer value) {
		setFaveid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FavoritesRecord value2(java.lang.Integer value) {
		setSongid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FavoritesRecord value3(java.lang.Long value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FavoritesRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Long value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FavoritesRecord
	 */
	public FavoritesRecord() {
		super(org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES);
	}

	/**
	 * Create a detached, initialised FavoritesRecord
	 */
	public FavoritesRecord(java.lang.Integer faveid, java.lang.Integer songid, java.lang.Long userid) {
		super(org.frostbite.karren.Database.Models.tables.Favorites.FAVORITES);

		setValue(0, faveid);
		setValue(1, songid);
		setValue(2, userid);
	}
}
