/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;


import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.tables.Interaction;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InteractionRecord extends UpdatableRecordImpl<InteractionRecord> implements Record11<Integer, String, String, Integer, String, String, String, Double, Byte, Byte, String> {

	private static final long serialVersionUID = -83459269;

	/**
	 * Setter for <code>KarrenDB.Interaction.InteractionID</code>.
	 */
	public void setInteractionid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>KarrenDB.Interaction.InteractionID</code>.
	 */
	public Integer getInteractionid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>KarrenDB.Interaction.Identifier</code>.
	 */
	public void setIdentifier(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>KarrenDB.Interaction.Identifier</code>.
	 */
	public String getIdentifier() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>KarrenDB.Interaction.HelpText</code>.
	 */
	public void setHelptext(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>KarrenDB.Interaction.HelpText</code>.
	 */
	public String getHelptext() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>KarrenDB.Interaction.Confidence</code>.
	 */
	public void setConfidence(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>KarrenDB.Interaction.Confidence</code>.
	 */
	public Integer getConfidence() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>KarrenDB.Interaction.PermissionLevel</code>.
	 */
	public void setPermissionlevel(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>KarrenDB.Interaction.PermissionLevel</code>.
	 */
	public String getPermissionlevel() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>KarrenDB.Interaction.ChannelOverride</code>.
	 */
	public void setChanneloverride(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>KarrenDB.Interaction.ChannelOverride</code>.
	 */
	public String getChanneloverride() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>KarrenDB.Interaction.Parameter</code>.
	 */
	public void setParameter(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>KarrenDB.Interaction.Parameter</code>.
	 */
	public String getParameter() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>KarrenDB.Interaction.PlaybackVolume</code>.
	 */
	public void setPlaybackvolume(Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>KarrenDB.Interaction.PlaybackVolume</code>.
	 */
	public Double getPlaybackvolume() {
		return (Double) getValue(7);
	}

	/**
	 * Setter for <code>KarrenDB.Interaction.SpecialInteraction</code>.
	 */
	public void setSpecialinteraction(Byte value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>KarrenDB.Interaction.SpecialInteraction</code>.
	 */
	public Byte getSpecialinteraction() {
		return (Byte) getValue(8);
	}

	/**
	 * Setter for <code>KarrenDB.Interaction.Enabled</code>.
	 */
	public void setEnabled(Byte value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>KarrenDB.Interaction.Enabled</code>.
	 */
	public Byte getEnabled() {
		return (Byte) getValue(9);
	}

	/**
	 * Setter for <code>KarrenDB.Interaction.GuildID</code>.
	 */
	public void setGuildid(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>KarrenDB.Interaction.GuildID</code>.
	 */
	public String getGuildid() {
		return (String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, String, String, Integer, String, String, String, Double, Byte, Byte, String> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, String, String, Integer, String, String, String, Double, Byte, Byte, String> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Interaction.INTERACTION.INTERACTIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Interaction.INTERACTION.IDENTIFIER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Interaction.INTERACTION.HELPTEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Interaction.INTERACTION.CONFIDENCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Interaction.INTERACTION.PERMISSIONLEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Interaction.INTERACTION.CHANNELOVERRIDE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Interaction.INTERACTION.PARAMETER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field8() {
		return Interaction.INTERACTION.PLAYBACKVOLUME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field9() {
		return Interaction.INTERACTION.SPECIALINTERACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field10() {
		return Interaction.INTERACTION.ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Interaction.INTERACTION.GUILDID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getInteractionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getIdentifier();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getHelptext();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getConfidence();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getPermissionlevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getChanneloverride();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getParameter();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value8() {
		return getPlaybackvolume();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value9() {
		return getSpecialinteraction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value10() {
		return getEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getGuildid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionRecord value1(Integer value) {
		setInteractionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionRecord value2(String value) {
		setIdentifier(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionRecord value3(String value) {
		setHelptext(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionRecord value4(Integer value) {
		setConfidence(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionRecord value5(String value) {
		setPermissionlevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionRecord value6(String value) {
		setChanneloverride(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionRecord value7(String value) {
		setParameter(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionRecord value8(Double value) {
		setPlaybackvolume(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionRecord value9(Byte value) {
		setSpecialinteraction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionRecord value10(Byte value) {
		setEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionRecord value11(String value) {
		setGuildid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, Double value8, Byte value9, Byte value10, String value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached InteractionRecord
	 */
	public InteractionRecord() {
		super(Interaction.INTERACTION);
	}

	/**
	 * Create a detached, initialised InteractionRecord
	 */
	public InteractionRecord(Integer interactionid, String identifier, String helptext, Integer confidence, String permissionlevel, String channeloverride, String parameter, Double playbackvolume, Byte specialinteraction, Byte enabled, String guildid) {
		super(Interaction.INTERACTION);

		setValue(0, interactionid);
		setValue(1, identifier);
		setValue(2, helptext);
		setValue(3, confidence);
		setValue(4, permissionlevel);
		setValue(5, channeloverride);
		setValue(6, parameter);
		setValue(7, playbackvolume);
		setValue(8, specialinteraction);
		setValue(9, enabled);
		setValue(10, guildid);
	}
}
