/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;


import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.tables.Interactiontemplate;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InteractiontemplateRecord extends UpdatableRecordImpl<InteractiontemplateRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = -1584333900;

	/**
	 * Setter for <code>KarrenDB.InteractionTemplate.TemplateID</code>.
	 */
	public void setTemplateid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>KarrenDB.InteractionTemplate.TemplateID</code>.
	 */
	public Integer getTemplateid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>KarrenDB.InteractionTemplate.Template</code>.
	 */
	public void setTemplate(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>KarrenDB.InteractionTemplate.Template</code>.
	 */
	public String getTemplate() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Interactiontemplate.INTERACTIONTEMPLATE.TEMPLATEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Interactiontemplate.INTERACTIONTEMPLATE.TEMPLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getTemplateid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTemplate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractiontemplateRecord value1(Integer value) {
		setTemplateid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractiontemplateRecord value2(String value) {
		setTemplate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractiontemplateRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached InteractiontemplateRecord
	 */
	public InteractiontemplateRecord() {
		super(Interactiontemplate.INTERACTIONTEMPLATE);
	}

	/**
	 * Create a detached, initialised InteractiontemplateRecord
	 */
	public InteractiontemplateRecord(Integer templateid, String template) {
		super(Interactiontemplate.INTERACTIONTEMPLATE);

		setValue(0, templateid);
		setValue(1, template);
	}
}
