/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;


import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.tables.Interactionfailuretemplate;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InteractionfailuretemplateRecord extends UpdatableRecordImpl<InteractionfailuretemplateRecord> implements Record3<Integer, Integer, Integer> {

	private static final long serialVersionUID = 79134337;

	/**
	 * Setter for <code>KarrenDB.InteractionFailureTemplate.FailureTemplateID</code>.
	 */
	public void setFailuretemplateid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>KarrenDB.InteractionFailureTemplate.FailureTemplateID</code>.
	 */
	public Integer getFailuretemplateid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>KarrenDB.InteractionFailureTemplate.InteractionID</code>.
	 */
	public void setInteractionid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>KarrenDB.InteractionFailureTemplate.InteractionID</code>.
	 */
	public Integer getInteractionid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>KarrenDB.InteractionFailureTemplate.TemplateID</code>.
	 */
	public void setTemplateid(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>KarrenDB.InteractionFailureTemplate.TemplateID</code>.
	 */
	public Integer getTemplateid() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<Integer, Integer, Integer> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Interactionfailuretemplate.INTERACTIONFAILURETEMPLATE.FAILURETEMPLATEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Interactionfailuretemplate.INTERACTIONFAILURETEMPLATE.INTERACTIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Interactionfailuretemplate.INTERACTIONFAILURETEMPLATE.TEMPLATEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getFailuretemplateid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getInteractionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getTemplateid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionfailuretemplateRecord value1(Integer value) {
		setFailuretemplateid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionfailuretemplateRecord value2(Integer value) {
		setInteractionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionfailuretemplateRecord value3(Integer value) {
		setTemplateid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionfailuretemplateRecord values(Integer value1, Integer value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached InteractionfailuretemplateRecord
	 */
	public InteractionfailuretemplateRecord() {
		super(Interactionfailuretemplate.INTERACTIONFAILURETEMPLATE);
	}

	/**
	 * Create a detached, initialised InteractionfailuretemplateRecord
	 */
	public InteractionfailuretemplateRecord(Integer failuretemplateid, Integer interactionid, Integer templateid) {
		super(Interactionfailuretemplate.INTERACTIONFAILURETEMPLATE);

		setValue(0, failuretemplateid);
		setValue(1, interactionid);
		setValue(2, templateid);
	}
}
