/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;


import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.tables.Interactionvoicefile;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InteractionvoicefileRecord extends UpdatableRecordImpl<InteractionvoicefileRecord> implements Record3<Integer, String, Integer> {

	private static final long serialVersionUID = 185665123;

	/**
	 * Setter for <code>KarrenDB.InteractionVoiceFile.VoiceFileID</code>.
	 */
	public void setVoicefileid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>KarrenDB.InteractionVoiceFile.VoiceFileID</code>.
	 */
	public Integer getVoicefileid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>KarrenDB.InteractionVoiceFile.VoiceFileLocation</code>.
	 */
	public void setVoicefilelocation(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>KarrenDB.InteractionVoiceFile.VoiceFileLocation</code>.
	 */
	public String getVoicefilelocation() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>KarrenDB.InteractionVoiceFile.InteractionID</code>.
	 */
	public void setInteractionid(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>KarrenDB.InteractionVoiceFile.InteractionID</code>.
	 */
	public Integer getInteractionid() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Interactionvoicefile.INTERACTIONVOICEFILE.VOICEFILEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Interactionvoicefile.INTERACTIONVOICEFILE.VOICEFILELOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Interactionvoicefile.INTERACTIONVOICEFILE.INTERACTIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getVoicefileid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getVoicefilelocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getInteractionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionvoicefileRecord value1(Integer value) {
		setVoicefileid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionvoicefileRecord value2(String value) {
		setVoicefilelocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionvoicefileRecord value3(Integer value) {
		setInteractionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionvoicefileRecord values(Integer value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached InteractionvoicefileRecord
	 */
	public InteractionvoicefileRecord() {
		super(Interactionvoicefile.INTERACTIONVOICEFILE);
	}

	/**
	 * Create a detached, initialised InteractionvoicefileRecord
	 */
	public InteractionvoicefileRecord(Integer voicefileid, String voicefilelocation, Integer interactionid) {
		super(Interactionvoicefile.INTERACTIONVOICEFILE);

		setValue(0, voicefileid);
		setValue(1, voicefilelocation);
		setValue(2, interactionid);
	}
}
