/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;


import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.tables.Interactionpermissionerrortemplate;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InteractionpermissionerrortemplateRecord extends UpdatableRecordImpl<InteractionpermissionerrortemplateRecord> implements Record3<Integer, Integer, Integer> {

	private static final long serialVersionUID = 799325800;

	/**
	 * Setter for <code>KarrenDB.InteractionPermissionErrorTemplate.PermErrorID</code>.
	 */
	public void setPermerrorid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>KarrenDB.InteractionPermissionErrorTemplate.PermErrorID</code>.
	 */
	public Integer getPermerrorid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>KarrenDB.InteractionPermissionErrorTemplate.InteractionID</code>.
	 */
	public void setInteractionid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>KarrenDB.InteractionPermissionErrorTemplate.InteractionID</code>.
	 */
	public Integer getInteractionid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>KarrenDB.InteractionPermissionErrorTemplate.TemplateID</code>.
	 */
	public void setTemplateid(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>KarrenDB.InteractionPermissionErrorTemplate.TemplateID</code>.
	 */
	public Integer getTemplateid() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<Integer, Integer, Integer> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Interactionpermissionerrortemplate.INTERACTIONPERMISSIONERRORTEMPLATE.PERMERRORID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Interactionpermissionerrortemplate.INTERACTIONPERMISSIONERRORTEMPLATE.INTERACTIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Interactionpermissionerrortemplate.INTERACTIONPERMISSIONERRORTEMPLATE.TEMPLATEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getPermerrorid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getInteractionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getTemplateid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionpermissionerrortemplateRecord value1(Integer value) {
		setPermerrorid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionpermissionerrortemplateRecord value2(Integer value) {
		setInteractionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionpermissionerrortemplateRecord value3(Integer value) {
		setTemplateid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InteractionpermissionerrortemplateRecord values(Integer value1, Integer value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached InteractionpermissionerrortemplateRecord
	 */
	public InteractionpermissionerrortemplateRecord() {
		super(Interactionpermissionerrortemplate.INTERACTIONPERMISSIONERRORTEMPLATE);
	}

	/**
	 * Create a detached, initialised InteractionpermissionerrortemplateRecord
	 */
	public InteractionpermissionerrortemplateRecord(Integer permerrorid, Integer interactionid, Integer templateid) {
		super(Interactionpermissionerrortemplate.INTERACTIONPERMISSIONERRORTEMPLATE);

		setValue(0, permerrorid);
		setValue(1, interactionid);
		setValue(2, templateid);
	}
}
