/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RadioDjRecord extends org.jooq.impl.UpdatableRecordImpl<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> {

	/**
	 * Setter for <code>database.radio_dj.ID</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>database.radio_dj.ID</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>database.radio_dj.displayName</code>.
	 */
	public void setDisplayname(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>database.radio_dj.displayName</code>.
	 */
	public java.lang.String getDisplayname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>database.radio_dj.connectName</code>.
	 */
	public void setConnectname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>database.radio_dj.connectName</code>.
	 */
	public java.lang.String getConnectname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>database.radio_dj.streamName</code>.
	 */
	public void setStreamname(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>database.radio_dj.streamName</code>.
	 */
	public java.lang.String getStreamname() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>database.radio_dj.djPicture</code>.
	 */
	public void setDjpicture(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>database.radio_dj.djPicture</code>.
	 */
	public java.lang.String getDjpicture() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>database.radio_dj.active</code>.
	 */
	public void setActive(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>database.radio_dj.active</code>.
	 */
	public java.lang.Integer getActive() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ.DISPLAYNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ.CONNECTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ.STREAMNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ.DJPICTURE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ.ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDisplayname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getConnectname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getStreamname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getDjpicture();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioDjRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioDjRecord value2(java.lang.String value) {
		setDisplayname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioDjRecord value3(java.lang.String value) {
		setConnectname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioDjRecord value4(java.lang.String value) {
		setStreamname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioDjRecord value5(java.lang.String value) {
		setDjpicture(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioDjRecord value6(java.lang.Integer value) {
		setActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioDjRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.Integer value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RadioDjRecord
	 */
	public RadioDjRecord() {
		super(org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ);
	}

	/**
	 * Create a detached, initialised RadioDjRecord
	 */
	public RadioDjRecord(java.lang.Integer id, java.lang.String displayname, java.lang.String connectname, java.lang.String streamname, java.lang.String djpicture, java.lang.Integer active) {
		super(org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ);

		setValue(0, id);
		setValue(1, displayname);
		setValue(2, connectname);
		setValue(3, streamname);
		setValue(4, djpicture);
		setValue(5, active);
	}
}
