/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SongdbRecord extends org.jooq.impl.UpdatableRecordImpl<org.frostbite.karren.Database.Models.tables.records.SongdbRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Long, java.lang.Byte> {


	/**
	 * Setter for <code>database.songdb.ID</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>database.songdb.ID</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>database.songdb.SongTitle</code>.
	 */
	public void setSongtitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>database.songdb.SongTitle</code>.
	 */
	public java.lang.String getSongtitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>database.songdb.LPTime</code>.
	 */
	public void setLptime(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>database.songdb.LPTime</code>.
	 */
	public java.lang.Long getLptime() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>database.songdb.PlayCount</code>.
	 */
	public void setPlaycount(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>database.songdb.PlayCount</code>.
	 */
	public java.lang.Integer getPlaycount() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>database.songdb.FavCount</code>.
	 */
	public void setFavcount(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>database.songdb.FavCount</code>.
	 */
	public java.lang.Integer getFavcount() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>database.songdb.songduration</code>.
	 */
	public void setSongduration(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>database.songdb.songduration</code>.
	 */
	public java.lang.Long getSongduration() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>database.songdb.durationlock</code>.
	 */
	public void setDurationlock(java.lang.Byte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>database.songdb.durationlock</code>.
	 */
	public java.lang.Byte getDurationlock() {
		return (java.lang.Byte) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Long, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Long, java.lang.Byte> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.frostbite.karren.Database.Models.tables.Songdb.SONGDB.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.frostbite.karren.Database.Models.tables.Songdb.SONGDB.SONGTITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return org.frostbite.karren.Database.Models.tables.Songdb.SONGDB.LPTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return org.frostbite.karren.Database.Models.tables.Songdb.SONGDB.PLAYCOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return org.frostbite.karren.Database.Models.tables.Songdb.SONGDB.FAVCOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return org.frostbite.karren.Database.Models.tables.Songdb.SONGDB.SONGDURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field7() {
		return org.frostbite.karren.Database.Models.tables.Songdb.SONGDB.DURATIONLOCK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSongtitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getLptime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getPlaycount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getFavcount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getSongduration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value7() {
		return getDurationlock();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value2(java.lang.String value) {
		setSongtitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value3(java.lang.Long value) {
		setLptime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value4(java.lang.Integer value) {
		setPlaycount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value5(java.lang.Integer value) {
		setFavcount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value6(java.lang.Long value) {
		setSongduration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value7(java.lang.Byte value) {
		setDurationlock(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Long value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Long value6, java.lang.Byte value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SongdbRecord
	 */
	public SongdbRecord() {
		super(org.frostbite.karren.Database.Models.tables.Songdb.SONGDB);
	}

	/**
	 * Create a detached, initialised SongdbRecord
	 */
	public SongdbRecord(java.lang.Integer id, java.lang.String songtitle, java.lang.Long lptime, java.lang.Integer playcount, java.lang.Integer favcount, java.lang.Long songduration, java.lang.Byte durationlock) {
		super(org.frostbite.karren.Database.Models.tables.Songdb.SONGDB);

		setValue(0, id);
		setValue(1, songtitle);
		setValue(2, lptime);
		setValue(3, playcount);
		setValue(4, favcount);
		setValue(5, songduration);
		setValue(6, durationlock);
	}
}
