/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends org.jooq.impl.UpdatableRecordImpl<org.frostbite.karren.Database.Models.tables.records.UserRecord> implements org.jooq.Record6<java.lang.Long, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 555823007;

	/**
	 * Setter for <code>KarrenDB.User.UserID</code>.
	 */
	public void setUserid(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>KarrenDB.User.UserID</code>.
	 */
	public java.lang.Long getUserid() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>KarrenDB.User.TimeLeft</code>.
	 */
	public void setTimeleft(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>KarrenDB.User.TimeLeft</code>.
	 */
	public java.sql.Timestamp getTimeleft() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>KarrenDB.User.DJName</code>.
	 */
	public void setDjname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>KarrenDB.User.DJName</code>.
	 */
	public java.lang.String getDjname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>KarrenDB.User.DJPicture</code>.
	 */
	public void setDjpicture(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>KarrenDB.User.DJPicture</code>.
	 */
	public java.lang.String getDjpicture() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>KarrenDB.User.DJActive</code>.
	 */
	public void setDjactive(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>KarrenDB.User.DJActive</code>.
	 */
	public java.lang.Integer getDjactive() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>KarrenDB.User.DJStreamName</code>.
	 */
	public void setDjstreamname(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>KarrenDB.User.DJStreamName</code>.
	 */
	public java.lang.String getDjstreamname() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.frostbite.karren.Database.Models.tables.User.USER.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return org.frostbite.karren.Database.Models.tables.User.USER.TIMELEFT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.frostbite.karren.Database.Models.tables.User.USER.DJNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.frostbite.karren.Database.Models.tables.User.USER.DJPICTURE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return org.frostbite.karren.Database.Models.tables.User.USER.DJACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return org.frostbite.karren.Database.Models.tables.User.USER.DJSTREAMNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getTimeleft();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDjname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDjpicture();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getDjactive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getDjstreamname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value1(java.lang.Long value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value2(java.sql.Timestamp value) {
		setTimeleft(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value3(java.lang.String value) {
		setDjname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value4(java.lang.String value) {
		setDjpicture(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value5(java.lang.Integer value) {
		setDjactive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value6(java.lang.String value) {
		setDjstreamname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord values(java.lang.Long value1, java.sql.Timestamp value2, java.lang.String value3, java.lang.String value4, java.lang.Integer value5, java.lang.String value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(org.frostbite.karren.Database.Models.tables.User.USER);
	}

	/**
	 * Create a detached, initialised UserRecord
	 */
	public UserRecord(java.lang.Long userid, java.sql.Timestamp timeleft, java.lang.String djname, java.lang.String djpicture, java.lang.Integer djactive, java.lang.String djstreamname) {
		super(org.frostbite.karren.Database.Models.tables.User.USER);

		setValue(0, userid);
		setValue(1, timeleft);
		setValue(2, djname);
		setValue(3, djpicture);
		setValue(4, djactive);
		setValue(5, djstreamname);
	}
}
