/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends org.jooq.impl.UpdatableRecordImpl<org.frostbite.karren.Database.Models.tables.records.UsersRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.Byte, java.lang.Long> {

	/**
	 * Setter for <code>database.users.IRCUserID</code>.
	 */
	public void setIrcuserid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>database.users.IRCUserID</code>.
	 */
	public java.lang.Integer getIrcuserid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>database.users.user</code>.
	 */
	public void setUser(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>database.users.user</code>.
	 */
	public java.lang.String getUser() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>database.users.botpart</code>.
	 */
	public void setBotpart(java.lang.Byte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>database.users.botpart</code>.
	 */
	public java.lang.Byte getBotpart() {
		return (java.lang.Byte) getValue(2);
	}

	/**
	 * Setter for <code>database.users.timepart</code>.
	 */
	public void setTimepart(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>database.users.timepart</code>.
	 */
	public java.lang.Long getTimepart() {
		return (java.lang.Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Byte, java.lang.Long> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Byte, java.lang.Long> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.frostbite.karren.Database.Models.tables.Users.USERS.IRCUSERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.frostbite.karren.Database.Models.tables.Users.USERS.USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field3() {
		return org.frostbite.karren.Database.Models.tables.Users.USERS.BOTPART;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return org.frostbite.karren.Database.Models.tables.Users.USERS.TIMEPART;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIrcuserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value3() {
		return getBotpart();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getTimepart();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value1(java.lang.Integer value) {
		setIrcuserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value2(java.lang.String value) {
		setUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value3(java.lang.Byte value) {
		setBotpart(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord value4(java.lang.Long value) {
		setTimepart(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Byte value3, java.lang.Long value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(org.frostbite.karren.Database.Models.tables.Users.USERS);
	}

	/**
	 * Create a detached, initialised UsersRecord
	 */
	public UsersRecord(java.lang.Integer ircuserid, java.lang.String user, java.lang.Byte botpart, java.lang.Long timepart) {
		super(org.frostbite.karren.Database.Models.tables.Users.USERS);

		setValue(0, ircuserid);
		setValue(1, user);
		setValue(2, botpart);
		setValue(3, timepart);
	}
}
