/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserfavesRecord extends org.jooq.impl.UpdatableRecordImpl<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.Integer> {


	/**
	 * Setter for <code>database.userfaves.ID</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>database.userfaves.ID</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>database.userfaves.user</code>.
	 */
	public void setUser(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>database.userfaves.user</code>.
	 */
	public java.lang.String getUser() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>database.userfaves.SongID</code>.
	 */
	public void setSongid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>database.userfaves.SongID</code>.
	 */
	public java.lang.Integer getSongid() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.frostbite.karren.Database.Models.tables.Userfaves.USERFAVES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.frostbite.karren.Database.Models.tables.Userfaves.USERFAVES.USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return org.frostbite.karren.Database.Models.tables.Userfaves.USERFAVES.SONGID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getSongid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserfavesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserfavesRecord value2(java.lang.String value) {
		setUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserfavesRecord value3(java.lang.Integer value) {
		setSongid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserfavesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserfavesRecord
	 */
	public UserfavesRecord() {
		super(org.frostbite.karren.Database.Models.tables.Userfaves.USERFAVES);
	}

	/**
	 * Create a detached, initialised UserfavesRecord
	 */
	public UserfavesRecord(java.lang.Integer id, java.lang.String user, java.lang.Integer songid) {
		super(org.frostbite.karren.Database.Models.tables.Userfaves.USERFAVES);

		setValue(0, id);
		setValue(1, user);
		setValue(2, songid);
	}
}
