/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WordcountsRecord extends org.jooq.impl.UpdatableRecordImpl<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.Long, java.sql.Timestamp> {

	private static final long serialVersionUID = 1368731475;

	/**
	 * Setter for <code>KarrenDB.WordCounts.WordID</code>.
	 */
	public void setWordid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>KarrenDB.WordCounts.WordID</code>.
	 */
	public java.lang.Integer getWordid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>KarrenDB.WordCounts.Word</code>.
	 */
	public void setWord(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>KarrenDB.WordCounts.Word</code>.
	 */
	public java.lang.String getWord() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>KarrenDB.WordCounts.Count</code>.
	 */
	public void setCount(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>KarrenDB.WordCounts.Count</code>.
	 */
	public java.lang.Long getCount() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>KarrenDB.WordCounts.CountStarted</code>.
	 */
	public void setCountstarted(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>KarrenDB.WordCounts.CountStarted</code>.
	 */
	public java.sql.Timestamp getCountstarted() {
		return (java.sql.Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Long, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Long, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS.WORDID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS.WORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS.COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS.COUNTSTARTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getWordid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getWord();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getCountstarted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WordcountsRecord value1(java.lang.Integer value) {
		setWordid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WordcountsRecord value2(java.lang.String value) {
		setWord(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WordcountsRecord value3(java.lang.Long value) {
		setCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WordcountsRecord value4(java.sql.Timestamp value) {
		setCountstarted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WordcountsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Long value3, java.sql.Timestamp value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WordcountsRecord
	 */
	public WordcountsRecord() {
		super(org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS);
	}

	/**
	 * Create a detached, initialised WordcountsRecord
	 */
	public WordcountsRecord(java.lang.Integer wordid, java.lang.String word, java.lang.Long count, java.sql.Timestamp countstarted) {
		super(org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS);

		setValue(0, wordid);
		setValue(1, word);
		setValue(2, count);
		setValue(3, countstarted);
	}
}
