/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.tables.Wordcounts;
import org.jooq.*;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WordcountsRecord extends UpdatableRecordImpl<WordcountsRecord> implements Record4<Integer, String, Long, Timestamp> {

	private static final long serialVersionUID = 1627998658;

	/**
	 * Setter for <code>KarrenDB.WordCounts.WordID</code>.
	 */
	public void setWordid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>KarrenDB.WordCounts.WordID</code>.
	 */
	public Integer getWordid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>KarrenDB.WordCounts.Word</code>.
	 */
	public void setWord(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>KarrenDB.WordCounts.Word</code>.
	 */
	public String getWord() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>KarrenDB.WordCounts.Count</code>.
	 */
	public void setCount(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>KarrenDB.WordCounts.Count</code>.
	 */
	public Long getCount() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>KarrenDB.WordCounts.CountStarted</code>.
	 */
	public void setCountstarted(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>KarrenDB.WordCounts.CountStarted</code>.
	 */
	public Timestamp getCountstarted() {
		return (Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, Long, Timestamp> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, Long, Timestamp> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Wordcounts.WORDCOUNTS.WORDID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Wordcounts.WORDCOUNTS.WORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return Wordcounts.WORDCOUNTS.COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Wordcounts.WORDCOUNTS.COUNTSTARTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getWordid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getWord();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getCountstarted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WordcountsRecord value1(Integer value) {
		setWordid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WordcountsRecord value2(String value) {
		setWord(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WordcountsRecord value3(Long value) {
		setCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WordcountsRecord value4(Timestamp value) {
		setCountstarted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WordcountsRecord values(Integer value1, String value2, Long value3, Timestamp value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WordcountsRecord
	 */
	public WordcountsRecord() {
		super(Wordcounts.WORDCOUNTS);
	}

	/**
	 * Create a detached, initialised WordcountsRecord
	 */
	public WordcountsRecord(Integer wordid, String word, Long count, Timestamp countstarted) {
		super(Wordcounts.WORDCOUNTS);

		setValue(0, wordid);
		setValue(1, word);
		setValue(2, count);
		setValue(3, countstarted);
	}
}
