/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.Karrendb;
import org.frostbite.karren.Database.Models.Keys;
import org.frostbite.karren.Database.Models.tables.records.GuildRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Guild extends TableImpl<GuildRecord> {

	private static final long serialVersionUID = -1640298498;

	/**
	 * The reference instance of <code>KarrenDB.Guild</code>
	 */
	public static final Guild GUILD = new Guild();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<GuildRecord> getRecordType() {
		return GuildRecord.class;
	}

	/**
	 * The column <code>KarrenDB.Guild.GuildID</code>.
	 */
	public final TableField<GuildRecord, String> GUILDID = createField("GuildID", org.jooq.impl.SQLDataType.VARCHAR.length(25).nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.Guild.GuildOwner</code>.
	 */
	public final TableField<GuildRecord, String> GUILDOWNER = createField("GuildOwner", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.Guild.GuildName</code>.
	 */
	public final TableField<GuildRecord, String> GUILDNAME = createField("GuildName", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.Guild.CommandPrefix</code>.
	 */
	public final TableField<GuildRecord, String> COMMANDPREFIX = createField("CommandPrefix", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * Create a <code>KarrenDB.Guild</code> table reference
	 */
	public Guild() {
		this("Guild", null);
	}

	/**
	 * Create an aliased <code>KarrenDB.Guild</code> table reference
	 */
	public Guild(String alias) {
		this(alias, GUILD);
	}

	private Guild(String alias, Table<GuildRecord> aliased) {
		this(alias, aliased, null);
	}

	private Guild(String alias, Table<GuildRecord> aliased, Field<?>[] parameters) {
		super(alias, Karrendb.KARRENDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<GuildRecord> getPrimaryKey() {
		return Keys.KEY_GUILD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<GuildRecord>> getKeys() {
		return Arrays.<UniqueKey<GuildRecord>>asList(Keys.KEY_GUILD_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Guild as(String alias) {
		return new Guild(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Guild rename(String name) {
		return new Guild(name, null);
	}
}
