/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.Karrendb;
import org.frostbite.karren.Database.Models.Keys;
import org.frostbite.karren.Database.Models.tables.records.InteractiontemplateRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Interactiontemplate extends TableImpl<InteractiontemplateRecord> {

	private static final long serialVersionUID = -986845215;

	/**
	 * The reference instance of <code>KarrenDB.InteractionTemplate</code>
	 */
	public static final Interactiontemplate INTERACTIONTEMPLATE = new Interactiontemplate();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InteractiontemplateRecord> getRecordType() {
		return InteractiontemplateRecord.class;
	}

	/**
	 * The column <code>KarrenDB.InteractionTemplate.TemplateID</code>.
	 */
	public final TableField<InteractiontemplateRecord, Integer> TEMPLATEID = createField("TemplateID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.InteractionTemplate.Template</code>.
	 */
	public final TableField<InteractiontemplateRecord, String> TEMPLATE = createField("Template", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>KarrenDB.InteractionTemplate</code> table reference
	 */
	public Interactiontemplate() {
		this("InteractionTemplate", null);
	}

	/**
	 * Create an aliased <code>KarrenDB.InteractionTemplate</code> table reference
	 */
	public Interactiontemplate(String alias) {
		this(alias, INTERACTIONTEMPLATE);
	}

	private Interactiontemplate(String alias, Table<InteractiontemplateRecord> aliased) {
		this(alias, aliased, null);
	}

	private Interactiontemplate(String alias, Table<InteractiontemplateRecord> aliased, Field<?>[] parameters) {
		super(alias, Karrendb.KARRENDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<InteractiontemplateRecord, Integer> getIdentity() {
		return Keys.IDENTITY_INTERACTIONTEMPLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<InteractiontemplateRecord> getPrimaryKey() {
		return Keys.KEY_INTERACTIONTEMPLATE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<InteractiontemplateRecord>> getKeys() {
		return Arrays.<UniqueKey<InteractiontemplateRecord>>asList(Keys.KEY_INTERACTIONTEMPLATE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Interactiontemplate as(String alias) {
		return new Interactiontemplate(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Interactiontemplate rename(String name) {
		return new Interactiontemplate(name, null);
	}
}
