/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.Karrendb;
import org.frostbite.karren.Database.Models.Keys;
import org.frostbite.karren.Database.Models.tables.records.InteractionpermissionerrortemplateRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Interactionpermissionerrortemplate extends TableImpl<InteractionpermissionerrortemplateRecord> {

	private static final long serialVersionUID = 1258219687;

	/**
	 * The reference instance of <code>KarrenDB.InteractionPermissionErrorTemplate</code>
	 */
	public static final Interactionpermissionerrortemplate INTERACTIONPERMISSIONERRORTEMPLATE = new Interactionpermissionerrortemplate();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InteractionpermissionerrortemplateRecord> getRecordType() {
		return InteractionpermissionerrortemplateRecord.class;
	}

	/**
	 * The column <code>KarrenDB.InteractionPermissionErrorTemplate.PermErrorID</code>.
	 */
	public final TableField<InteractionpermissionerrortemplateRecord, Integer> PERMERRORID = createField("PermErrorID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.InteractionPermissionErrorTemplate.InteractionID</code>.
	 */
	public final TableField<InteractionpermissionerrortemplateRecord, Integer> INTERACTIONID = createField("InteractionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.InteractionPermissionErrorTemplate.TemplateID</code>.
	 */
	public final TableField<InteractionpermissionerrortemplateRecord, Integer> TEMPLATEID = createField("TemplateID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>KarrenDB.InteractionPermissionErrorTemplate</code> table reference
	 */
	public Interactionpermissionerrortemplate() {
		this("InteractionPermissionErrorTemplate", null);
	}

	/**
	 * Create an aliased <code>KarrenDB.InteractionPermissionErrorTemplate</code> table reference
	 */
	public Interactionpermissionerrortemplate(String alias) {
		this(alias, INTERACTIONPERMISSIONERRORTEMPLATE);
	}

	private Interactionpermissionerrortemplate(String alias, Table<InteractionpermissionerrortemplateRecord> aliased) {
		this(alias, aliased, null);
	}

	private Interactionpermissionerrortemplate(String alias, Table<InteractionpermissionerrortemplateRecord> aliased, Field<?>[] parameters) {
		super(alias, Karrendb.KARRENDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<InteractionpermissionerrortemplateRecord, Integer> getIdentity() {
		return Keys.IDENTITY_INTERACTIONPERMISSIONERRORTEMPLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<InteractionpermissionerrortemplateRecord> getPrimaryKey() {
		return Keys.KEY_INTERACTIONPERMISSIONERRORTEMPLATE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<InteractionpermissionerrortemplateRecord>> getKeys() {
		return Arrays.<UniqueKey<InteractionpermissionerrortemplateRecord>>asList(Keys.KEY_INTERACTIONPERMISSIONERRORTEMPLATE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<InteractionpermissionerrortemplateRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<InteractionpermissionerrortemplateRecord, ?>>asList(Keys.FK_INTERACTIONPERMISSIONERRORTEMPLATE_INTERACTION1, Keys.FK_INTERACTIONPERMISSIONERRORTEMPLATE_INTERACTIONTEMPLATE1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Interactionpermissionerrortemplate as(String alias) {
		return new Interactionpermissionerrortemplate(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Interactionpermissionerrortemplate rename(String name) {
		return new Interactionpermissionerrortemplate(name, null);
	}
}
