/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.Karrendb;
import org.frostbite.karren.Database.Models.Keys;
import org.frostbite.karren.Database.Models.tables.records.InteractionRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Interaction extends TableImpl<InteractionRecord> {

	private static final long serialVersionUID = -2127233061;

	/**
	 * The reference instance of <code>KarrenDB.Interaction</code>
	 */
	public static final Interaction INTERACTION = new Interaction();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InteractionRecord> getRecordType() {
		return InteractionRecord.class;
	}

	/**
	 * The column <code>KarrenDB.Interaction.InteractionID</code>.
	 */
	public final TableField<InteractionRecord, Integer> INTERACTIONID = createField("InteractionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.Interaction.Identifier</code>.
	 */
	public final TableField<InteractionRecord, String> IDENTIFIER = createField("Identifier", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.Interaction.HelpText</code>.
	 */
	public final TableField<InteractionRecord, String> HELPTEXT = createField("HelpText", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.Interaction.Confidence</code>.
	 */
	public final TableField<InteractionRecord, Integer> CONFIDENCE = createField("Confidence", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.Interaction.PermissionLevel</code>.
	 */
	public final TableField<InteractionRecord, String> PERMISSIONLEVEL = createField("PermissionLevel", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>KarrenDB.Interaction.ChannelOverride</code>.
	 */
	public final TableField<InteractionRecord, String> CHANNELOVERRIDE = createField("ChannelOverride", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>KarrenDB.Interaction.Parameter</code>.
	 */
	public final TableField<InteractionRecord, String> PARAMETER = createField("Parameter", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>KarrenDB.Interaction.PlaybackVolume</code>.
	 */
	public final TableField<InteractionRecord, Double> PLAYBACKVOLUME = createField("PlaybackVolume", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>KarrenDB.Interaction.SpecialInteraction</code>.
	 */
	public final TableField<InteractionRecord, Byte> SPECIALINTERACTION = createField("SpecialInteraction", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.Interaction.Enabled</code>.
	 */
	public final TableField<InteractionRecord, Byte> ENABLED = createField("Enabled", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.Interaction.GuildID</code>.
	 */
	public final TableField<InteractionRecord, String> GUILDID = createField("GuildID", org.jooq.impl.SQLDataType.VARCHAR.length(25).nullable(false), this, "");

	/**
	 * Create a <code>KarrenDB.Interaction</code> table reference
	 */
	public Interaction() {
		this("Interaction", null);
	}

	/**
	 * Create an aliased <code>KarrenDB.Interaction</code> table reference
	 */
	public Interaction(String alias) {
		this(alias, INTERACTION);
	}

	private Interaction(String alias, Table<InteractionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Interaction(String alias, Table<InteractionRecord> aliased, Field<?>[] parameters) {
		super(alias, Karrendb.KARRENDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<InteractionRecord, Integer> getIdentity() {
		return Keys.IDENTITY_INTERACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<InteractionRecord> getPrimaryKey() {
		return Keys.KEY_INTERACTION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<InteractionRecord>> getKeys() {
		return Arrays.<UniqueKey<InteractionRecord>>asList(Keys.KEY_INTERACTION_PRIMARY, Keys.KEY_INTERACTION_IDENTIFIER_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<InteractionRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<InteractionRecord, ?>>asList(Keys.FK_INTERACTION_GUILD1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Interaction as(String alias) {
		return new Interaction(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Interaction rename(String name) {
		return new Interaction(name, null);
	}
}
