/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.Karrendb;
import org.frostbite.karren.Database.Models.Keys;
import org.frostbite.karren.Database.Models.tables.records.InteractionsuccesstemplateRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Interactionsuccesstemplate extends TableImpl<InteractionsuccesstemplateRecord> {

	private static final long serialVersionUID = -1554690286;

	/**
	 * The reference instance of <code>KarrenDB.InteractionSuccessTemplate</code>
	 */
	public static final Interactionsuccesstemplate INTERACTIONSUCCESSTEMPLATE = new Interactionsuccesstemplate();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InteractionsuccesstemplateRecord> getRecordType() {
		return InteractionsuccesstemplateRecord.class;
	}

	/**
	 * The column <code>KarrenDB.InteractionSuccessTemplate.SuccessID</code>.
	 */
	public final TableField<InteractionsuccesstemplateRecord, Integer> SUCCESSID = createField("SuccessID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.InteractionSuccessTemplate.InteractionID</code>.
	 */
	public final TableField<InteractionsuccesstemplateRecord, Integer> INTERACTIONID = createField("InteractionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.InteractionSuccessTemplate.TemplateID</code>.
	 */
	public final TableField<InteractionsuccesstemplateRecord, Integer> TEMPLATEID = createField("TemplateID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>KarrenDB.InteractionSuccessTemplate</code> table reference
	 */
	public Interactionsuccesstemplate() {
		this("InteractionSuccessTemplate", null);
	}

	/**
	 * Create an aliased <code>KarrenDB.InteractionSuccessTemplate</code> table reference
	 */
	public Interactionsuccesstemplate(String alias) {
		this(alias, INTERACTIONSUCCESSTEMPLATE);
	}

	private Interactionsuccesstemplate(String alias, Table<InteractionsuccesstemplateRecord> aliased) {
		this(alias, aliased, null);
	}

	private Interactionsuccesstemplate(String alias, Table<InteractionsuccesstemplateRecord> aliased, Field<?>[] parameters) {
		super(alias, Karrendb.KARRENDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<InteractionsuccesstemplateRecord, Integer> getIdentity() {
		return Keys.IDENTITY_INTERACTIONSUCCESSTEMPLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<InteractionsuccesstemplateRecord> getPrimaryKey() {
		return Keys.KEY_INTERACTIONSUCCESSTEMPLATE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<InteractionsuccesstemplateRecord>> getKeys() {
		return Arrays.<UniqueKey<InteractionsuccesstemplateRecord>>asList(Keys.KEY_INTERACTIONSUCCESSTEMPLATE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<InteractionsuccesstemplateRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<InteractionsuccesstemplateRecord, ?>>asList(Keys.FK_INTERACTIONSUCCESSTEMPLATE_INTERACTION1, Keys.FK_INTERACTIONSUCCESSTEMPLATE_INTERACTIONTEMPLATE1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Interactionsuccesstemplate as(String alias) {
		return new Interactionsuccesstemplate(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Interactionsuccesstemplate rename(String name) {
		return new Interactionsuccesstemplate(name, null);
	}
}
