/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.frostbite.karren.Database.Models.Karrendb;
import org.frostbite.karren.Database.Models.Keys;
import org.frostbite.karren.Database.Models.tables.records.InteractionfailuretemplateRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Interactionfailuretemplate extends TableImpl<InteractionfailuretemplateRecord> {

	private static final long serialVersionUID = 1670053491;

	/**
	 * The reference instance of <code>KarrenDB.InteractionFailureTemplate</code>
	 */
	public static final Interactionfailuretemplate INTERACTIONFAILURETEMPLATE = new Interactionfailuretemplate();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InteractionfailuretemplateRecord> getRecordType() {
		return InteractionfailuretemplateRecord.class;
	}

	/**
	 * The column <code>KarrenDB.InteractionFailureTemplate.FailureTemplateID</code>.
	 */
	public final TableField<InteractionfailuretemplateRecord, Integer> FAILURETEMPLATEID = createField("FailureTemplateID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.InteractionFailureTemplate.InteractionID</code>.
	 */
	public final TableField<InteractionfailuretemplateRecord, Integer> INTERACTIONID = createField("InteractionID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.InteractionFailureTemplate.TemplateID</code>.
	 */
	public final TableField<InteractionfailuretemplateRecord, Integer> TEMPLATEID = createField("TemplateID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>KarrenDB.InteractionFailureTemplate</code> table reference
	 */
	public Interactionfailuretemplate() {
		this("InteractionFailureTemplate", null);
	}

	/**
	 * Create an aliased <code>KarrenDB.InteractionFailureTemplate</code> table reference
	 */
	public Interactionfailuretemplate(String alias) {
		this(alias, INTERACTIONFAILURETEMPLATE);
	}

	private Interactionfailuretemplate(String alias, Table<InteractionfailuretemplateRecord> aliased) {
		this(alias, aliased, null);
	}

	private Interactionfailuretemplate(String alias, Table<InteractionfailuretemplateRecord> aliased, Field<?>[] parameters) {
		super(alias, Karrendb.KARRENDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<InteractionfailuretemplateRecord, Integer> getIdentity() {
		return Keys.IDENTITY_INTERACTIONFAILURETEMPLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<InteractionfailuretemplateRecord> getPrimaryKey() {
		return Keys.KEY_INTERACTIONFAILURETEMPLATE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<InteractionfailuretemplateRecord>> getKeys() {
		return Arrays.<UniqueKey<InteractionfailuretemplateRecord>>asList(Keys.KEY_INTERACTIONFAILURETEMPLATE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<InteractionfailuretemplateRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<InteractionfailuretemplateRecord, ?>>asList(Keys.FK_INTERACTIONFAILURETEMPLATE_INTERACTION1, Keys.FK_INTERACTIONFAILURETEMPLATE_INTERACTIONTEMPLATE1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Interactionfailuretemplate as(String alias) {
		return new Interactionfailuretemplate(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Interactionfailuretemplate rename(String name) {
		return new Interactionfailuretemplate(name, null);
	}
}
