/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables;

import org.frostbite.karren.Database.Models.Database;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RadioDj extends org.jooq.impl.TableImpl<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord> {

	/**
	 * The singleton instance of <code>database.radio_dj</code>
	 */
	public static final org.frostbite.karren.Database.Models.tables.RadioDj RADIO_DJ = new org.frostbite.karren.Database.Models.tables.RadioDj();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord> getRecordType() {
		return org.frostbite.karren.Database.Models.tables.records.RadioDjRecord.class;
	}

	/**
	 * The column <code>database.radio_dj.ID</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>database.radio_dj.displayName</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord, java.lang.String> DISPLAYNAME = createField("displayName", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>database.radio_dj.connectName</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord, java.lang.String> CONNECTNAME = createField("connectName", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>database.radio_dj.streamName</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord, java.lang.String> STREAMNAME = createField("streamName", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>database.radio_dj.djPicture</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord, java.lang.String> DJPICTURE = createField("djPicture", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>database.radio_dj.active</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord, java.lang.Integer> ACTIVE = createField("active", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>database.radio_dj</code> table reference
	 */
	public RadioDj() {
		this("radio_dj", null);
	}

	/**
	 * Create an aliased <code>database.radio_dj</code> table reference
	 */
	public RadioDj(java.lang.String alias) {
		this(alias, org.frostbite.karren.Database.Models.tables.RadioDj.RADIO_DJ);
	}

	private RadioDj(java.lang.String alias, org.jooq.Table<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord> aliased) {
		this(alias, aliased, null);
	}

	private RadioDj(java.lang.String alias, org.jooq.Table<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Database.DATABASE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord, java.lang.Integer> getIdentity() {
		return org.frostbite.karren.Database.Models.Keys.IDENTITY_RADIO_DJ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord> getPrimaryKey() {
		return org.frostbite.karren.Database.Models.Keys.KEY_RADIO_DJ_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.RadioDjRecord>>asList(org.frostbite.karren.Database.Models.Keys.KEY_RADIO_DJ_PRIMARY, org.frostbite.karren.Database.Models.Keys.KEY_RADIO_DJ_UNIQ_982FE985774A00A);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.frostbite.karren.Database.Models.tables.RadioDj as(java.lang.String alias) {
		return new org.frostbite.karren.Database.Models.tables.RadioDj(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.frostbite.karren.Database.Models.tables.RadioDj rename(java.lang.String name) {
		return new org.frostbite.karren.Database.Models.tables.RadioDj(name, null);
	}
}
