/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables;

import org.frostbite.karren.Database.Models.Database;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Songdb extends org.jooq.impl.TableImpl<org.frostbite.karren.Database.Models.tables.records.SongdbRecord> {

	/**
	 * The singleton instance of <code>database.songdb</code>
	 */
	public static final org.frostbite.karren.Database.Models.tables.Songdb SONGDB = new org.frostbite.karren.Database.Models.tables.Songdb();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.frostbite.karren.Database.Models.tables.records.SongdbRecord> getRecordType() {
		return org.frostbite.karren.Database.Models.tables.records.SongdbRecord.class;
	}

	/**
	 * The column <code>database.songdb.ID</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.SongdbRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>database.songdb.SongTitle</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.SongdbRecord, java.lang.String> SONGTITLE = createField("SongTitle", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * The column <code>database.songdb.LPTime</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.SongdbRecord, java.lang.Long> LPTIME = createField("LPTime", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>database.songdb.PlayCount</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.SongdbRecord, java.lang.Integer> PLAYCOUNT = createField("PlayCount", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>database.songdb.FavCount</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.SongdbRecord, java.lang.Integer> FAVCOUNT = createField("FavCount", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>database.songdb.songduration</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.SongdbRecord, java.lang.Long> SONGDURATION = createField("songduration", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>database.songdb.durationlock</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.SongdbRecord, java.lang.Byte> DURATIONLOCK = createField("durationlock", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>database.songdb</code> table reference
	 */
	public Songdb() {
		this("songdb", null);
	}

	/**
	 * Create an aliased <code>database.songdb</code> table reference
	 */
	public Songdb(java.lang.String alias) {
		this(alias, org.frostbite.karren.Database.Models.tables.Songdb.SONGDB);
	}

	private Songdb(java.lang.String alias, org.jooq.Table<org.frostbite.karren.Database.Models.tables.records.SongdbRecord> aliased) {
		this(alias, aliased, null);
	}

	private Songdb(java.lang.String alias, org.jooq.Table<org.frostbite.karren.Database.Models.tables.records.SongdbRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Database.DATABASE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.SongdbRecord, java.lang.Integer> getIdentity() {
		return org.frostbite.karren.Database.Models.Keys.IDENTITY_SONGDB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.SongdbRecord> getPrimaryKey() {
		return org.frostbite.karren.Database.Models.Keys.KEY_SONGDB_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.SongdbRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.SongdbRecord>>asList(org.frostbite.karren.Database.Models.Keys.KEY_SONGDB_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.frostbite.karren.Database.Models.tables.Songdb as(java.lang.String alias) {
		return new org.frostbite.karren.Database.Models.tables.Songdb(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.frostbite.karren.Database.Models.tables.Songdb rename(java.lang.String name) {
		return new org.frostbite.karren.Database.Models.tables.Songdb(name, null);
	}
}
