/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables;

import org.frostbite.karren.Database.Models.Database;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userfaves extends org.jooq.impl.TableImpl<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord> {

	/**
	 * The singleton instance of <code>database.userfaves</code>
	 */
	public static final org.frostbite.karren.Database.Models.tables.Userfaves USERFAVES = new org.frostbite.karren.Database.Models.tables.Userfaves();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord> getRecordType() {
		return org.frostbite.karren.Database.Models.tables.records.UserfavesRecord.class;
	}

	/**
	 * The column <code>database.userfaves.ID</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>database.userfaves.user</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord, java.lang.String> USER = createField("user", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>database.userfaves.SongID</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord, java.lang.Integer> SONGID = createField("SongID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>database.userfaves</code> table reference
	 */
	public Userfaves() {
		this("userfaves", null);
	}

	/**
	 * Create an aliased <code>database.userfaves</code> table reference
	 */
	public Userfaves(java.lang.String alias) {
		this(alias, org.frostbite.karren.Database.Models.tables.Userfaves.USERFAVES);
	}

	private Userfaves(java.lang.String alias, org.jooq.Table<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Userfaves(java.lang.String alias, org.jooq.Table<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Database.DATABASE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord, java.lang.Integer> getIdentity() {
		return org.frostbite.karren.Database.Models.Keys.IDENTITY_USERFAVES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord> getPrimaryKey() {
		return org.frostbite.karren.Database.Models.Keys.KEY_USERFAVES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.UserfavesRecord>>asList(org.frostbite.karren.Database.Models.Keys.KEY_USERFAVES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.frostbite.karren.Database.Models.tables.Userfaves as(java.lang.String alias) {
		return new org.frostbite.karren.Database.Models.tables.Userfaves(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.frostbite.karren.Database.Models.tables.Userfaves rename(java.lang.String name) {
		return new org.frostbite.karren.Database.Models.tables.Userfaves(name, null);
	}
}
