/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<org.frostbite.karren.Database.Models.tables.records.UserRecord> {

	/**
	 * The singleton instance of <code>KarrenDB.User</code>
	 */
	public static final org.frostbite.karren.Database.Models.tables.User USER = new org.frostbite.karren.Database.Models.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.frostbite.karren.Database.Models.tables.records.UserRecord> getRecordType() {
		return org.frostbite.karren.Database.Models.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>KarrenDB.User.UserID</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.UserRecord, java.lang.Long> USERID = createField("UserID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.User.TimeLeft</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.UserRecord, java.sql.Timestamp> TIMELEFT = createField("TimeLeft", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>KarrenDB.User.DJName</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.UserRecord, java.lang.String> DJNAME = createField("DJName", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.User.DJPicture</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.UserRecord, java.lang.String> DJPICTURE = createField("DJPicture", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>KarrenDB.User.DJActive</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.UserRecord, java.lang.Integer> DJACTIVE = createField("DJActive", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>KarrenDB.User.DJStreamName</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.UserRecord, java.lang.String> DJSTREAMNAME = createField("DJStreamName", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaulted(true), this, "");

	/**
	 * Create a <code>KarrenDB.User</code> table reference
	 */
	public User() {
		this("User", null);
	}

	/**
	 * Create an aliased <code>KarrenDB.User</code> table reference
	 */
	public User(java.lang.String alias) {
		this(alias, org.frostbite.karren.Database.Models.tables.User.USER);
	}

	private User(java.lang.String alias, org.jooq.Table<org.frostbite.karren.Database.Models.tables.records.UserRecord> aliased) {
		this(alias, aliased, null);
	}

	private User(java.lang.String alias, org.jooq.Table<org.frostbite.karren.Database.Models.tables.records.UserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.frostbite.karren.Database.Models.Karrendb.KARRENDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.UserRecord> getPrimaryKey() {
		return org.frostbite.karren.Database.Models.Keys.KEY_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.UserRecord>>asList(org.frostbite.karren.Database.Models.Keys.KEY_USER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.frostbite.karren.Database.Models.tables.User as(java.lang.String alias) {
		return new org.frostbite.karren.Database.Models.tables.User(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.frostbite.karren.Database.Models.tables.User rename(java.lang.String name) {
		return new org.frostbite.karren.Database.Models.tables.User(name, null);
	}
}
