/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wordcounts extends org.jooq.impl.TableImpl<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord> {
	/**
	 * The singleton instance of <code>KarrenDB.WordCounts</code>
	 */
	public static final org.frostbite.karren.Database.Models.tables.Wordcounts WORDCOUNTS = new org.frostbite.karren.Database.Models.tables.Wordcounts();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord> getRecordType() {
		return org.frostbite.karren.Database.Models.tables.records.WordcountsRecord.class;
	}

	/**
	 * The column <code>KarrenDB.WordCounts.WordID</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord, java.lang.Integer> WORDID = createField("WordID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.WordCounts.Word</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord, java.lang.String> WORD = createField("Word", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>KarrenDB.WordCounts.Count</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord, java.lang.Long> COUNT = createField("Count", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>KarrenDB.WordCounts.CountStarted</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord, java.sql.Timestamp> COUNTSTARTED = createField("CountStarted", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>KarrenDB.WordCounts</code> table reference
	 */
	public Wordcounts() {
		this("WordCounts", null);
	}

	/**
	 * Create an aliased <code>KarrenDB.WordCounts</code> table reference
	 */
	public Wordcounts(java.lang.String alias) {
		this(alias, org.frostbite.karren.Database.Models.tables.Wordcounts.WORDCOUNTS);
	}

	private Wordcounts(java.lang.String alias, org.jooq.Table<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Wordcounts(java.lang.String alias, org.jooq.Table<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.frostbite.karren.Database.Models.Karrendb.KARRENDB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord, java.lang.Integer> getIdentity() {
		return org.frostbite.karren.Database.Models.Keys.IDENTITY_WORDCOUNTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord> getPrimaryKey() {
		return org.frostbite.karren.Database.Models.Keys.KEY_WORDCOUNTS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordcountsRecord>>asList(org.frostbite.karren.Database.Models.Keys.KEY_WORDCOUNTS_PRIMARY, org.frostbite.karren.Database.Models.Keys.KEY_WORDCOUNTS_WORD);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.frostbite.karren.Database.Models.tables.Wordcounts as(java.lang.String alias) {
		return new org.frostbite.karren.Database.Models.tables.Wordcounts(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.frostbite.karren.Database.Models.tables.Wordcounts rename(java.lang.String name) {
		return new org.frostbite.karren.Database.Models.tables.Wordcounts(name, null);
	}
}
