/**
 * This class is generated by jOOQ
 */
package org.frostbite.karren.Database.Models.tables;

import org.frostbite.karren.Database.Models.Database;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WordCounts extends org.jooq.impl.TableImpl<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord> {

	/**
	 * The singleton instance of <code>database.word_counts</code>
	 */
	public static final org.frostbite.karren.Database.Models.tables.WordCounts WORD_COUNTS = new org.frostbite.karren.Database.Models.tables.WordCounts();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord> getRecordType() {
		return org.frostbite.karren.Database.Models.tables.records.WordCountsRecord.class;
	}

	/**
	 * The column <code>database.word_counts.id</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>database.word_counts.word</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord, java.lang.String> WORD = createField("word", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>database.word_counts.count</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord, java.lang.Long> COUNT = createField("count", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>database.word_counts.count_started</code>.
	 */
	public final org.jooq.TableField<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord, java.sql.Timestamp> COUNT_STARTED = createField("count_started", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>database.word_counts</code> table reference
	 */
	public WordCounts() {
		this("word_counts", null);
	}

	/**
	 * Create an aliased <code>database.word_counts</code> table reference
	 */
	public WordCounts(java.lang.String alias) {
		this(alias, org.frostbite.karren.Database.Models.tables.WordCounts.WORD_COUNTS);
	}

	private WordCounts(java.lang.String alias, org.jooq.Table<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord> aliased) {
		this(alias, aliased, null);
	}

	private WordCounts(java.lang.String alias, org.jooq.Table<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Database.DATABASE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord, java.lang.Integer> getIdentity() {
		return org.frostbite.karren.Database.Models.Keys.IDENTITY_WORD_COUNTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord> getPrimaryKey() {
		return org.frostbite.karren.Database.Models.Keys.KEY_WORD_COUNTS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.frostbite.karren.Database.Models.tables.records.WordCountsRecord>>asList(org.frostbite.karren.Database.Models.Keys.KEY_WORD_COUNTS_PRIMARY, org.frostbite.karren.Database.Models.Keys.KEY_WORD_COUNTS_WORD);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.frostbite.karren.Database.Models.tables.WordCounts as(java.lang.String alias) {
		return new org.frostbite.karren.Database.Models.tables.WordCounts(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.frostbite.karren.Database.Models.tables.WordCounts rename(java.lang.String name) {
		return new org.frostbite.karren.Database.Models.tables.WordCounts(name, null);
	}
}
