SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `Guild` (
  `GuildID` varchar(25) NOT NULL,
  `GuildOwner` varchar(100) NOT NULL,
  `GuildName` varchar(100) NOT NULL,
  `CommandPrefix` varchar(100) NOT NULL,
  `RollDifficulty` int(11) NOT NULL DEFAULT '-1',
  `MaxVolume` int(11) NOT NULL DEFAULT '40',
  `RandomRange` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `GuildUser` (
  `GuildUserID` int(11) NOT NULL,
  `UserID` bigint(20) NOT NULL,
  `GuildID` varchar(25) CHARACTER SET utf8 NOT NULL,
  `RollTimeout` datetime DEFAULT NULL,
  `IgnoreCommands` tinyint(1) NOT NULL,
  `RollsSinceLastClear` int(11) NOT NULL DEFAULT '0',
  `TotalRolls` int(11) NOT NULL DEFAULT '0',
  `WinningRolls` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Reminder` (
  `ReminderID` int(11) NOT NULL,
  `AuthorID` bigint(11) NOT NULL,
  `TargetID` int(11) NOT NULL,
  `ReminderTime` datetime NOT NULL,
  `Message` text NOT NULL,
  `ReminderSent` tinyint(1) NOT NULL,
  `ChannelID` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `User` (
  `UserID` bigint(20) NOT NULL,
  `TimeLeft` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `WordCounts` (
  `WordID` int(11) NOT NULL,
  `Word` varchar(100) NOT NULL,
  `Count` bigint(20) NOT NULL DEFAULT '0',
  `CountStarted` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `Guild`
  ADD PRIMARY KEY (`GuildID`);

ALTER TABLE `GuildUser`
  ADD PRIMARY KEY (`GuildUserID`),
  ADD UNIQUE KEY `UserID_2` (`UserID`,`GuildID`),
  ADD KEY `GuildID` (`GuildID`),
  ADD KEY `UserID` (`UserID`) USING BTREE;

ALTER TABLE `Reminder`
  ADD PRIMARY KEY (`ReminderID`),
  ADD KEY `TargetID` (`TargetID`),
  ADD KEY `AuthorID` (`AuthorID`),
  ADD KEY `ChannelID` (`ChannelID`);

ALTER TABLE `User`
  ADD PRIMARY KEY (`UserID`);

ALTER TABLE `WordCounts`
  ADD PRIMARY KEY (`WordID`),
  ADD UNIQUE KEY `Word` (`Word`);


ALTER TABLE `GuildUser`
  MODIFY `GuildUserID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3003;

ALTER TABLE `Reminder`
  MODIFY `ReminderID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=73;

ALTER TABLE `WordCounts`
  MODIFY `WordID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=93;


ALTER TABLE `GuildUser`
  ADD CONSTRAINT `FK_GUILD_USER` FOREIGN KEY (`GuildID`) REFERENCES `Guild` (`GuildID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `GuildUser_ibfk_1` FOREIGN KEY (`UserID`) REFERENCES `User` (`UserID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Reminder`
  ADD CONSTRAINT `Reminder_ibfk_2` FOREIGN KEY (`TargetID`) REFERENCES `GuildUser` (`GuildUserID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `Reminder_ibfk_3` FOREIGN KEY (`AuthorID`) REFERENCES `User` (`UserID`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
