# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the jda-port branch
  push:
    branches: [ jda-port ]
  pull_request:
    branches: [ jda-port ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Gradle +x
        run: chmod +x gradlew
      - name: Run Gradle Build
        run: ./gradlew build
      - run: mkdir staging && cp -R build/* staging && cp -R conf/ staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
